name: Blencraft
version: '${project.version}'
main: me.matsubara.blencraft.BlencraftPlugin
api-version: 1.13
author: Matsubara
description: Create 3D models using armor stands.

commands:
  blencraft:
    description: main command.
    usage: /<command>